# This workflow will build a test version of the package and publish it to TestPyPI for testing

name: Publish to TestPyPI
on:
  workflow_run:
    workflows: [Test Py Versions and OS]
    types: [completed]
    branches: [dev_env]

jobs:
  # Job 1: Build the dist files
  build-package:
    name: Build dist
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v2.0
      with:
        pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_name: "testpypi"
        repository_url: "https://test.pypi.org/legacy/"
