# Create and publish docs website
name: Publish Docs Page

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      id: setuppython
      with:
        python-version: '3.x'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        key: ${{ github.ref }}
        path: .cache

    - name: Install mkdocs
      run: |
        pip install mkdocs
        pip install mkdocs-material

    - name: Deploy page
      run: mkdocs gh-deploy --force